### ISSUE TITLE
person attributes consistency

### ISSUE THREAD

**Issue by deligkaris** [jburke5/microsim#68]
Some person attributes do not have the same type in the entirety of their list and I was expecting the types of the list elements to be consistent.

eg:
anyPhysicalActivity: [1, True, True, True, True, True, True, True, True, True, True]
afib: [0.002033779535137486, False, False...]
alcoholPerWeek: [<AlcoholCategory.FOURTEENORMORE: 3>, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

Is this important?

Also, since alcohol per week is part of the gcp stroke model: is the number 2 in the above example representing the category SEVENTOTHIRTEEN, or does it represent the actual number of alcoholic drinks? I suspect it is the first one but I need to ensure I got this right for the gcp stroke model...

**Comment by jburke5** [comment]
the “#2”, i suspect represents the category SEVENTOTHIRTEEN

so, i suspect those errors aren’t likely to lead to bugs because Python usually treats “1” and True” as the same thing and original variables like the alcohol level are usually treated the same as the underlying number…

but, they could lead to issues. so, this seems like an issue that we shoudl try to fix — but, i don’t quite know that its a bug yet! i could imagine it becoming a bug at some point though!

**Comment by deligkaris** [comment]
OK, I will leave this as a to do item...

To decrease the probability of introducing bugs by making the element types consistent, I am thinking to modify the 0 index elements to match the rest, since the rest of the elements are used in multiple places....

What do you think?

**Comment by jburke5** [comment]
i think that probably, the index 0 elements look a little better — those are the more detailed and specifically typed data elements…I think we want those things to line up...

**Comment by deligkaris** [comment]
OK, I will modify the rest and do a lot of testing....

**Comment by deligkaris** [comment]
Done.
